/** 真实天文数据 + 可视化比例尺 */

export const DISTANCE_PER_AU = 80;
export const SIZE_SCALE = 0.00045;

export const TEXTURE_BASE =
  'https://cdn.jsdelivr.net/gh/mrdoob/three.js@r170/examples/textures/planets/';

/** 太阳系行星表面贴图见 js/planetTextures.js（Solar System Scope / NASA，含法线） */

export const PLANETS = [
  {
    id: 'sun',
    name: '太阳',
    nameEn: 'Sun',
    color: '#ffcc33',
    emissive: '#ff8800',
    radiusKm: 696340,
    orbitAU: 0,
    periodDays: 0,
    desc: '太阳系的中心恒星，占系统总质量的 99.86%，为八大行星提供光和热。',
    texture: null,
    emissiveIntensity: 2.5,
    isStar: true,
    profile: {
      life: '无（恒星等离子体环境）',
      habitability: '不可居住',
      difficulty: '10 / 10',
      travelTime: '约 7～10 年（近日探测器，如帕克）· 表面无法抵达',
      surface: '等离子体 / 无固体表面',
      temperature: '核心约 1,500 万°C',
      atmosphere: '氢、氦为主',
      environment:
        '核心温度高达千万度，辐射与等离子体喷流贯穿日冕。没有固体地表可供立足，日冕物质抛射与太阳风粒子以极高速度向外扩散，是太阳系最极端的高能环境。',
    },
  },
  {
    id: 'mercury',
    name: '水星',
    nameEn: 'Mercury',
    color: '#b5b5b5',
    radiusKm: 2439.7,
    orbitAU: 0.387,
    periodDays: 88,
    desc: '距太阳最近的行星，表面温差极大，没有大气层。',
    texture: null,
    tilt: 0.034,
    rotationHours: 1407.6,
    profile: {
      life: '无已知生命',
      habitability: '极低',
      difficulty: '9 / 10',
      travelTime: '约 3～6 年（无人探测器级）',
      surface: '岩石行星，无液态水',
      temperature: '白天 430°C / 夜晚 -180°C',
      atmosphere: '极稀薄外逸层，近乎真空',
      environment:
        '布满撞击坑与悬崖的灰色荒原，几乎没有大气保护。向阳面被太阳炙烤至数百摄氏度，背阳面则骤降至零下近两百度；昼夜温差超过六百度，地表直接暴露于太阳辐射与宇宙射线。',
    },
  },
  {
    id: 'venus',
    name: '金星',
    nameEn: 'Venus',
    color: '#e8cda0',
    radiusKm: 6051.8,
    orbitAU: 0.723,
    periodDays: 225,
    desc: '太阳系中最热的行星，浓厚二氧化碳大气造成强烈温室效应。',
    texture: null,
    tilt: 177.4,
    rotationHours: -5832.5,
    profile: {
      life: '无已知生命',
      habitability: '极低（温室效应极端）',
      difficulty: '9 / 10',
      travelTime: '约 4～8 个月（载人理论值）',
      surface: '岩石行星，硫酸云层',
      temperature: '约 465°C（地表均温）',
      atmosphere: '二氧化碳 96.5%、氮 3.5%',
      environment:
        '厚重硫酸云层笼罩全星球，温室效应使地表如同高压炼狱。大气压约为地球的 92 倍，硫酸液滴与闪电风暴在云层中肆虐；地表温度足以熔化铅，雷达探测显示遍布火山平原与山脉，但没有任何已知生命能在此生存。',
    },
  },
  {
    id: 'earth',
    name: '地球',
    nameEn: 'Earth',
    color: '#4a90d9',
    radiusKm: 6371,
    orbitAU: 1.0,
    periodDays: 365.25,
    desc: '目前已知唯一存在生命的行星，71% 表面被海洋覆盖。',
    texture: 'earth_atmos_2048.jpg',
    bumpTexture: 'earth_normal_2048.jpg',
    specularTexture: null,
    cloudsTexture: 'earth_clouds_1024.png',
    tilt: 23.44,
    hasLandmarks: true,
    children: ['moon'],
    rotationHours: 23.9345,
    profile: {
      life: '约 870 万物种（含人类 80 亿）',
      habitability: '极高 · 已广泛居住',
      difficulty: '2 / 10',
      travelTime: '约 3 天（近地轨道）',
      surface: '岩石行星，71% 海洋覆盖',
      temperature: '全球均温约 15°C',
      atmosphere: '氮 78%、氧 21%、微量其他',
      environment:
        '蔚蓝海洋与白云覆盖的宜居世界，拥有稳定液态水圈与板块运动。从极地冰盖到热带雨林、沙漠与高原，气候带丰富多样；磁场与大气层共同屏蔽大部分太阳风与宇宙辐射，是已知唯一演化出复杂生命与文明的行星。',
    },
  },
  {
    id: 'moon',
    name: '月球',
    nameEn: 'Moon',
    color: '#c8c8c8',
    radiusKm: 1737.4,
    orbitAU: 0,
    orbitParent: 'earth',
    orbitDistanceKm: 384400,
    periodDays: 27.3,
    desc: '地球唯一的天然卫星，表面布满陨石坑与月海。',
    texture: 'moon_1024.jpg',
    tilt: 6.68,
    hasLandmarks: true,
    isMoon: true,
    profile: {
      life: '无已知生命',
      habitability: '低（需封闭基地）',
      difficulty: '5 / 10',
      travelTime: '约 3～4 天（地月转移）',
      surface: '岩石卫星，无大气',
      temperature: '白天 127°C / 夜晚 -173°C',
      atmosphere: '近乎真空（微量氩、氦）',
      environment:
        '灰白月壤覆盖的寂静荒原，遍布环形山与深色月海玄武岩。没有大气与磁场，昼夜温差极大；长期受微陨石轰击，表面形成细腻风化层。地下可能存在水冰，是未来深空基地的热门选址。',
    },
  },
  {
    id: 'mars',
    name: '火星',
    nameEn: 'Mars',
    color: '#c1440e',
    radiusKm: 3389.5,
    orbitAU: 1.524,
    periodDays: 687,
    desc: '红色行星，拥有太阳系最大的火山奥林匹斯山与峡谷水手号谷。',
    texture: null,
    bumpTexture: null,
    tilt: 25.19,
    rotationHours: 24.623,
    hasLandmarks: true,
    profile: {
      life: '无已知生命',
      habitability: '低（改造研究中）',
      difficulty: '7 / 10',
      travelTime: '约 6～9 个月（最优窗口）',
      surface: '岩石行星，极地冰冠',
      temperature: '平均约 -65°C',
      atmosphere: '二氧化碳 95%、氮 2.7%、氩 1.6%',
      environment:
        '铁锈色荒漠绵延数千里，沙丘、古河道与撞击坑交织成荒凉地貌。稀薄大气压不足地球的 1%，无法阻挡紫外线与宇宙辐射；全球性沙尘暴可遮蔽天空数周。极地冠由水冰与干冰组成，地下可能蕴藏大量水冰，是人类火星殖民与改造研究的核心目标。',
    },
  },
  {
    id: 'jupiter',
    name: '木星',
    nameEn: 'Jupiter',
    color: '#c88b5a',
    radiusKm: 69911,
    orbitAU: 5.203,
    periodDays: 4333,
    desc: '太阳系最大行星，著名的大红斑风暴已持续数百年。',
    texture: null,
    tilt: 3.13,
    rotationHours: 9.925,
    hasLandmarks: true,
    profile: {
      life: '无（气态巨行星）',
      habitability: '不可居住',
      difficulty: '10 / 10',
      travelTime: '约 5～7 年（探测器级）',
      surface: '气态，无固体表面',
      temperature: '云顶约 -110°C',
      atmosphere: '氢 89%、氦 10%、甲烷等',
      environment:
        '没有可供站立的固体表面，越往下气压与温度急剧上升。顶层可见氨与甲烷形成的彩色云带，大红斑是持续数百年的巨型风暴；深处可能存在液态金属氢海洋。强烈辐射带与闪电风暴使探测器难以长期停留。',
    },
  },
  {
    id: 'saturn',
    name: '土星',
    nameEn: 'Saturn',
    color: '#e8d5a3',
    radiusKm: 58232,
    orbitAU: 9.537,
    periodDays: 10759,
    desc: '以壮丽光环著称的气态巨行星，光环主要由冰粒组成。',
    texture: null,
    tilt: 26.73,
    hasRings: true,
    rotationHours: 10.656,
    hasLandmarks: true,
    profile: {
      life: '无（气态巨行星）',
      habitability: '不可居住',
      difficulty: '10 / 10',
      travelTime: '约 7～10 年（探测器级）',
      surface: '气态，可能有金属氢核心',
      temperature: '云顶约 -140°C',
      atmosphere: '氢 96%、氦 3%、甲烷等',
      environment:
        '淡黄色云带与壮丽的行星环是土星最显著的特征。光环主要由水冰颗粒构成，分为主环与稀疏的外环；云顶风速超过 1,800 km/h。同样缺乏固体表面，内部可能有岩石核心与金属氢层，环境极端而壮丽。',
    },
  },
  {
    id: 'uranus',
    name: '天王星',
    nameEn: 'Uranus',
    color: '#7de3f4',
    radiusKm: 25362,
    orbitAU: 19.191,
    periodDays: 30687,
    desc: '冰巨星，自转轴几乎横躺，呈现独特的蓝绿色。',
    texture: null,
    tilt: 97.77,
    rotationHours: -17.24,
    hasLandmarks: true,
    profile: {
      life: '无（冰巨星）',
      habitability: '不可居住',
      difficulty: '10 / 10',
      travelTime: '约 12～15 年（探测器级）',
      surface: '气液混合，无固体表面',
      temperature: '云顶约 -195°C',
      atmosphere: '氢 83%、氦 15%、甲烷 2%',
      environment:
        '自转轴几乎与公转轨道平行，呈现「侧躺」姿态，造成极端季节变化。甲烷吸收红光，赋予其独特的青绿色外观；高层云层稀薄而寒冷，内部热量异常微弱，整体氛围静谧而神秘。',
    },
  },
  {
    id: 'neptune',
    name: '海王星',
    nameEn: 'Neptune',
    color: '#3e54e8',
    radiusKm: 24622,
    orbitAU: 30.07,
    periodDays: 60190,
    desc: '太阳系最外侧行星，风速可达每小时 2100 公里。',
    texture: null,
    tilt: 28.32,
    rotationHours: 16.11,
    hasLandmarks: true,
    profile: {
      life: '无（冰巨星）',
      habitability: '不可居住',
      difficulty: '10 / 10',
      travelTime: '约 12～15 年（探测器级）',
      surface: '气液混合，无固体表面',
      temperature: '云顶约 -200°C',
      atmosphere: '氢 80%、氦 19%、甲烷等',
      environment:
        '深蓝色的冰巨行星，拥有太阳系最强劲的风暴系统，风速可达 2,100 km/h。高层甲烷云赋予其钴蓝色调；与天王星类似没有固体表面，但内部热流相对活跃，驱动了可见的云带与暗斑结构。',
    },
  },
  {
    id: 'pluto',
    name: '冥王星',
    nameEn: 'Pluto',
    color: '#c9b8a8',
    radiusKm: 1188.3,
    orbitAU: 39.48,
    periodDays: 90560,
    desc: '矮行星，新视野号揭示其拥有心形冰川平原与蓝色大气霾。',
    texture: null,
    tilt: 122.53,
    rotationHours: -153.3,
    hasLandmarks: true,
    isKBO: true,
    profile: {
      life: '无已知生命',
      habitability: '不可居住',
      difficulty: '10 / 10',
      travelTime: '约 9～12 年（新视野号级）',
      surface: '氮冰平原与水冰山脉',
      temperature: '约 -230°C',
      atmosphere: '氮、甲烷、一氧化碳（稀薄）',
      environment:
        '心形平原「汤博」由氮冰构成，周围环绕水冰山脉与深色有机物质区域。接近远日点时大气几乎冻结回落表；近近日点则升起薄霾，使天空呈现淡蓝色。表面温度极低，是柯伊伯带最具标志性的矮行星世界。',
    },
  },
  {
    id: 'eris',
    name: '阋神星',
    nameEn: 'Eris',
    color: '#e8e0d8',
    radiusKm: 1163,
    orbitAU: 67.78,
    periodDays: 203830,
    desc: '柯伊伯带最大的矮行星之一，曾引发冥王星「降级」讨论。',
    texture: null,
    tilt: 78.3,
    rotationHours: 67.0,
    isKBO: true,
    profile: {
      life: '无',
      habitability: '不可居住',
      difficulty: '10 / 10',
      travelTime: '约 20+ 年（探测器级）',
      surface: '甲烷冰覆盖',
      temperature: '约 -243°C',
      atmosphere: '无稳定大气',
      environment:
        '表面以甲烷冰为主，反射率极高，在柯伊伯带中格外明亮。轨道远日点距离极大，阳光微弱，环境接近绝对零度；几乎没有地质活动，保存了太阳系早期冰冻物质的原始状态。',
    },
  },
  {
    id: 'makemake',
    name: '鸟神星',
    nameEn: 'Makemake',
    color: '#c8b0a0',
    radiusKm: 715,
    orbitAU: 45.79,
    periodDays: 112897,
    desc: '经典柯伊伯带天体，表面富含甲烷冰。',
    texture: null,
    tilt: 29.0,
    rotationHours: 22.5,
    isKBO: true,
    profile: {
      life: '无',
      habitability: '不可居住',
      difficulty: '10 / 10',
      travelTime: '约 15+ 年',
      surface: '甲烷/乙烷冰',
      temperature: '约 -239°C',
      atmosphere: '无',
      environment:
        '富含甲烷与乙烷冰的明亮表面，是经典柯伊伯带天体之一。缺乏显著大气，光照极其微弱；低温使挥发物基本凝固，表面长期维持稳定的冰冻化学状态。',
    },
  },
  {
    id: 'haumea',
    name: '妊神星',
    nameEn: 'Haumea',
    color: '#d8d0c8',
    radiusKm: 816,
    orbitAU: 43.13,
    periodDays: 103774,
    desc: '高速自转的椭球形矮行星，拥有光环与两颗卫星。',
    texture: null,
    tilt: 126.0,
    rotationHours: 3.92,
    isKBO: true,
    profile: {
      life: '无',
      habitability: '不可居住',
      difficulty: '10 / 10',
      travelTime: '约 14+ 年',
      surface: '水冰外壳',
      temperature: '约 -241°C',
      atmosphere: '无',
      environment:
        '高速自转使其呈现椭球体外形，表面为水冰外壳，并拥有一圈稀薄光环。自转周期仅约 4 小时，内部结构可能分化出岩石核心；是柯伊伯带中形态最独特的天体之一。',
    },
  },
  {
    id: 'quaoar',
    name: '夸奥尔',
    nameEn: 'Quaoar',
    color: '#b8a898',
    radiusKm: 555,
    orbitAU: 43.41,
    periodDays: 105366,
    desc: '柯伊伯带大型天体，以美洲原住民神话命名。',
    texture: null,
    isKBO: true,
    profile: {
      life: '无',
      habitability: '不可居住',
      difficulty: '10 / 10',
      travelTime: '约 14+ 年',
      surface: '冰岩混合',
      temperature: '约 -220°C',
      atmosphere: '无',
      environment:
        '大型冰岩混合天体，表面可能存在结晶水冰与暗色有机质斑块。轨道相对稳定，阳光微弱；环境寒冷干燥，是研究外太阳系早期物质组成的样本。',
    },
  },
  {
    id: 'orcus',
    name: '亡神星',
    nameEn: 'Orcus',
    color: '#a89888',
    radiusKm: 458,
    orbitAU: 39.17,
    periodDays: 89620,
    desc: '冥王星轨道共振天体，表面有水冰与有机化合物。',
    texture: null,
    isKBO: true,
    profile: {
      life: '无',
      habitability: '不可居住',
      difficulty: '10 / 10',
      travelTime: '约 12+ 年',
      surface: '水冰与暗斑',
      temperature: '约 -218°C',
      atmosphere: '无',
      environment:
        '与冥王星形成 3:2 轨道共振的冥族天体，表面水冰与暗斑交错。可能曾遭受古代撞击，化学成分与冥王星有相似之处；长期停留在寒冷、黑暗的柯伊伯带外围区域。',
    },
  },
  {
    id: 'sedna',
    name: '塞德娜',
    nameEn: 'Sedna',
    color: '#cc8878',
    radiusKm: 498,
    orbitAU: 506.8,
    periodDays: 4153000,
    desc: '极端远日点天体，轨道深入外太阳系，周期约 1.1 万年。',
    texture: null,
    isKBO: true,
    profile: {
      life: '无',
      habitability: '不可居住',
      difficulty: '10 / 10',
      travelTime: '数百年（现有技术不可达）',
      surface: '甲烷/氮冰',
      temperature: '约 -240°C',
      atmosphere: '无',
      environment:
        '轨道远日点达 975 AU，是已知最极端的太阳系天体之一。表面由甲烷与氮冰覆盖，常年处于接近绝对零度的黑暗环境；公转周期约 1.1 万年，阳光微弱如星点，堪称外太阳系的「孤独世界」。',
    },
  },
];

export const EARTH_LANDMARKS = [
  { name: '北京', lat: 39.9, lon: 116.4, major: true },
  { name: '上海', lat: 31.2, lon: 121.5, major: true },
  { name: '东京', lat: 35.7, lon: 139.7, major: true },
  { name: '首尔', lat: 37.6, lon: 127.0 },
  { name: '新德里', lat: 28.6, lon: 77.2, major: true },
  { name: '孟买', lat: 19.1, lon: 72.9 },
  { name: '迪拜', lat: 25.2, lon: 55.3 },
  { name: '莫斯科', lat: 55.8, lon: 37.6, major: true },
  { name: '伦敦', lat: 51.5, lon: -0.1, major: true },
  { name: '巴黎', lat: 48.9, lon: 2.3, major: true },
  { name: '柏林', lat: 52.5, lon: 13.4 },
  { name: '罗马', lat: 41.9, lon: 12.5 },
  { name: '开罗', lat: 30.0, lon: 31.2, major: true },
  { name: '拉各斯', lat: 6.5, lon: 3.4 },
  { name: '纽约', lat: 40.7, lon: -74.0, major: true },
  { name: '华盛顿', lat: 38.9, lon: -77.0 },
  { name: '洛杉矶', lat: 34.1, lon: -118.2, major: true },
  { name: '芝加哥', lat: 41.9, lon: -87.6 },
  { name: '墨西哥城', lat: 19.4, lon: -99.1, major: true },
  { name: '圣保罗', lat: -23.5, lon: -46.6, major: true },
  { name: '布宜诺斯艾利斯', lat: -34.6, lon: -58.4 },
  { name: '悉尼', lat: -33.9, lon: 151.2, major: true },
  { name: '墨尔本', lat: -37.8, lon: 145.0 },
  { name: '新加坡', lat: 1.3, lon: 103.8 },
  { name: '香港', lat: 22.3, lon: 114.2, major: true },
  { name: '喜马拉雅山', lat: 27.9, lon: 86.9, major: true },
  { name: '珠穆朗玛峰', lat: 27.99, lon: 86.92, major: true },
  { name: '撒哈拉沙漠', lat: 23.5, lon: 12.0 },
  { name: '亚马逊雨林', lat: -3.5, lon: -62.0, major: true },
  { name: '刚果盆地', lat: 0.5, lon: 22.0 },
  { name: '西伯利亚', lat: 60.0, lon: 100.0 },
  { name: '格陵兰', lat: 72.0, lon: -40.0 },
  { name: '南极', lat: -82.0, lon: 0.0, major: true },
  { name: '北极', lat: 84.0, lon: 0.0 },
  { name: '夏威夷', lat: 19.9, lon: -155.5 },
  { name: '阿拉斯加', lat: 64.0, lon: -153.0 },
  { name: '巴拿马运河', lat: 9.1, lon: -79.7 },
  { name: '苏伊士运河', lat: 30.5, lon: 32.3 },
  { name: '地中海', lat: 36.0, lon: 18.0 },
  { name: '里海', lat: 42.0, lon: 51.0 },
  { name: '贝加尔湖', lat: 53.5, lon: 108.0 },
  { name: '长江口', lat: 31.4, lon: 121.5 },
  { name: '黄河三角洲', lat: 37.5, lon: 118.5 },
  { name: '尼罗河三角洲', lat: 30.5, lon: 31.2 },
  { name: '密西西比河口', lat: 29.0, lon: -89.2 },
  { name: '大堡礁', lat: -18.3, lon: 147.0, major: true },
  { name: '东非大裂谷', lat: -2.0, lon: 36.0 },
  { name: '科罗拉多大峡谷', lat: 36.1, lon: -112.1 },
  { name: '大峡谷', lat: -25.0, lon: 133.0 },
];

export const MOON_LANDMARKS = [
  { name: '静海 (阿波罗11号着陆点)', lat: 0.67, lon: 23.47, major: true },
  { name: '风暴洋', lat: 18.0, lon: -59.0, major: true },
  { name: '雨海', lat: 15.0, lon: -30.0 },
  { name: '澄海', lat: 4.0, lon: 17.0 },
  { name: '危海', lat: 17.0, lon: 59.0 },
  { name: '冷海', lat: 44.0, lon: -30.0 },
  { name: '东海', lat: 14.0, lon: 60.0 },
  { name: '南海', lat: -40.0, lon: -15.0 },
  { name: '莫斯科海', lat: 20.0, lon: 147.0 },
  { name: '第谷陨石坑', lat: -43.3, lon: -11.0, major: true },
  { name: '哥白尼陨石坑', lat: 9.7, lon: -20.0, major: true },
  { name: '开普勒陨石坑', lat: 8.1, lon: -38.0 },
  { name: '阿里斯塔克陨石坑', lat: 23.7, lon: -47.4 },
  { name: '柏拉图陨石坑', lat: 51.6, lon: -9.4 },
  { name: '克拉维斯陨石坑', lat: -58.4, lon: -14.4 },
  { name: '阿波罗盆地', lat: -36.0, lon: -151.0 },
  { name: '南极-艾特肯盆地', lat: -56.0, lon: 180.0, major: true },
  { name: '薛定谔陨石坑', lat: -75.0, lon: 134.0 },
  { name: '阿波罗17号着陆点', lat: 20.2, lon: 30.8 },
  { name: '阿波罗15号着陆点', lat: 26.1, lon: 3.6 },
];

export const MARS_LANDMARKS = [
  { name: '奥林匹斯山', lat: 18.65, lon: -133.8, major: true },
  { name: '水手号谷', lat: -14.0, lon: -59.0, major: true },
  { name: '希腊平原', lat: 42.0, lon: 70.0 },
  { name: '水手9号谷', lat: -14.0, lon: 50.0 },
  { name: '盖尔陨石坑', lat: -5.4, lon: 137.8, major: true },
  { name: '杰泽罗陨石坑', lat: 18.4, lon: 77.5, major: true },
  { name: '北极冠', lat: 85.0, lon: 0.0 },
  { name: '南极冠', lat: -87.0, lon: 0.0 },
  { name: '埃律西昂山', lat: 25.0, lon: 147.0 },
  { name: '阿尔西亚山', lat: -9.0, lon: -120.0 },
];

export const JUPITER_LANDMARKS = [
  { name: '大红斑', lat: -22.0, lon: 0.0, major: true },
  { name: '小红斑', lat: -28.0, lon: 120.0 },
  { name: '赤道带', lat: 0.0, lon: 0.0, major: true },
  { name: '北温带', lat: 25.0, lon: 0.0 },
  { name: '南温带', lat: -25.0, lon: 0.0 },
  { name: '伽利略区', lat: 10.0, lon: 60.0 },
];

export const GENERIC_LANDMARKS = {
  saturn: [
    { name: '北极六边形', lat: 78.0, lon: 0.0, major: true },
    { name: '赤道风暴带', lat: 0.0, lon: 0.0 },
    { name: 'A环', lat: 0.0, lon: 45.0, major: true },
    { name: 'B环', lat: 0.0, lon: 90.0 },
    { name: '卡西尼缝', lat: 0.0, lon: 135.0 },
  ],
  uranus: [
    { name: '北极', lat: 90.0, lon: 0.0 },
    { name: '南极', lat: -90.0, lon: 0.0 },
    { name: '赤道暗带', lat: 0.0, lon: 0.0, major: true },
    { name: '南半球云带', lat: -30.0, lon: 60.0 },
  ],
  neptune: [
    { name: '大暗斑', lat: -20.0, lon: 0.0, major: true },
    { name: '斯库特云', lat: -42.0, lon: 30.0 },
    { name: '北极', lat: 85.0, lon: 0.0 },
    { name: '赤道急流', lat: 0.0, lon: 0.0, major: true },
  ],
  pluto: [
    { name: '斯普特尼克平原', lat: 18.0, lon: -30.0, major: true },
    { name: '汤博区', lat: 10.0, lon: 150.0, major: true },
    { name: '克苏鲁暗斑', lat: -10.0, lon: 60.0 },
    { name: '北极', lat: 85.0, lon: 0.0 },
    { name: '南极', lat: -85.0, lon: 0.0, major: true },
  ],
  eris: [
    { name: '主表面', lat: 0.0, lon: 0.0, major: true },
    { name: '迪丝诺美亚（卫星）', lat: 30.0, lon: 90.0 },
  ],
  makemake: [{ name: '甲烷冰冠', lat: 60.0, lon: 0.0, major: true }],
  haumea: [
    { name: '赤道脊', lat: 0.0, lon: 0.0, major: true },
    { name: '希亚卡（卫星）', lat: 20.0, lon: 120.0 },
  ],
  quaoar: [{ name: '主表面', lat: 0.0, lon: 0.0, major: true }],
  orcus: [{ name: '水冰区', lat: 15.0, lon: 45.0, major: true }],
  sedna: [{ name: '极冠', lat: 80.0, lon: 0.0, major: true }],
  mercury: [
    { name: '卡洛里斯盆地', lat: 30.0, lon: 160.0, major: true },
    { name: '北极', lat: 85.0, lon: 0.0 },
    { name: '南极', lat: -85.0, lon: 0.0 },
    { name: '贝多芬盆地', lat: -37.0, lon: 124.0 },
  ],
  venus: [
    { name: '伊师塔高原', lat: 65.0, lon: 3.0, major: true },
    { name: '阿佛洛狄忒高地', lat: -5.0, lon: 60.0, major: true },
    { name: '麦克斯韦山', lat: 65.0, lon: 3.0 },
    { name: '拉克什米高原', lat: 50.0, lon: 340.0 },
  ],
  sun: [
    { name: '光球层', lat: 0.0, lon: 0.0, major: true },
    { name: '色球层', lat: 30.0, lon: 45.0 },
    { name: '日冕', lat: 60.0, lon: 90.0, major: true },
    { name: '太阳黑子区', lat: -15.0, lon: 120.0 },
  ],
};

export function getLandmarks(planetId) {
  switch (planetId) {
    case 'earth': return EARTH_LANDMARKS;
    case 'moon': return MOON_LANDMARKS;
    case 'mars': return MARS_LANDMARKS;
    case 'jupiter': return JUPITER_LANDMARKS;
    default: return GENERIC_LANDMARKS[planetId] || [];
  }
}

export function orbitDistance(data) {
  if (data.orbitParent) {
    const parent = PLANETS.find((p) => p.id === data.orbitParent);
    const parentR = Math.max(parent.radiusKm * SIZE_SCALE, 0.35);
    // 真实地月距约 60 倍地球半径；可视化压缩到 ~10 倍，避免月球"脱离"地球轨道
    const VISUAL_MOON_RATIO = 10;
    return parentR * VISUAL_MOON_RATIO;
  }
  return data.orbitAU * DISTANCE_PER_AU;
}

export function visualRadius(data) {
  if (data.isStar) return 12;
  if (data.isMoon) return Math.max(data.radiusKm * SIZE_SCALE, 1.6);
  if (data.id === 'mercury') return Math.max(data.radiusKm * SIZE_SCALE, 0.55);
  if (data.isKBO) return Math.max(data.radiusKm * SIZE_SCALE, 0.28);
  return Math.max(data.radiusKm * SIZE_SCALE, 0.35);
}

export function latLonToVector3(lat, lon, radius, offset = 1.02) {
  const phi = (90 - lat) * (Math.PI / 180);
  const theta = (lon + 180) * (Math.PI / 180);
  const r = radius * offset;
  return {
    x: -r * Math.sin(phi) * Math.cos(theta),
    y: r * Math.cos(phi),
    z: r * Math.sin(phi) * Math.sin(theta),
  };
}
